CREATE TABLE neat_liquors (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    liquor_name TEXT NOT NULL,
    brand_name TEXT NOT NULL,
    producer TEXT NOT NULL,
    origin TEXT NOT NULL,
    liquor_type TEXT NOT NULL,
    liquor_age TEXT NOT NULL,
    proof TEXT NOT NULL, 
    price TEXT NOT NULL,
    rating TEXT NOT NULL,
    content TEXT,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);